[build]
      command   = "npm run build"
      publish   = "build"
      functions = "netlify/functions"
[[redirects]]
      from = "/*"
      to = "/index.html"
      status = 200
[functions]
      directory = "netlify/functions"
      node_bundler = "esbuild"

[functions.getProjectImages]
  include_files = ["public/**/*"]